
* Introduction

In recent years, significant advances have been made in the use deep learning models in computer musical instruments. Supervised learning methods have now long been used by designers to allow versatile forms of control and mappings1 (wekinator). On the other hand, the development of unsupervised machine learning have made possible novel forms of sound manipulation and generation. 

Despite there have been many works that have created new methods and systems that document developments of deep learning technology in computer musical instruments and human computer interface, there has been a lack of discussion about how these systems have shifted the discussion around agency and causality, and the balance between commendation and material oriented design and performance of computer musical instrument and human computer interfaces.

In this work, we attempts to identified a performative /relational space/ generated by a gestural deep learning driven musical instruments system to analyse new agential balances provided by deep learning system in the design and use of computer musical instruments. For this investigation we design a system of pose estimation for more than one person, which outputs feed a supervised neural network to control both representational and non-representational latent spaces of a sound corpus and sound synthesis. As a form of evaluation, researchers aims to explore the political-agential and aesthetics scopes through the analysis of the intersections between the different spaces driven by deep learning systems from the tradition materialist-contemporary philosophy and the tradition of interactive art.

This repository contains pieces of software that build the instrument that serves to evaluate these insights about musical instruments and machine learning.

* How to use it

The repository contains three pieces of code. Two Python scripts that use MediaPipe to get landmarks from the body. One is for getting the landmarks in live mode from a video camera, and the other is to get a series of pose and their respective landmarks from a bunch of pictures. The later saves the data in a JSON file, and a copy of the picture analyzed in which can be visualized the landmarks. 

The thrid piece of code is a Supercollider Script that implement a Regression Neural Networks suing FluCoMa to control the latent space of RAVE that stands for Realtime Audio Variational autoEncoder. It is a deep learning model developed by IRCAM (Institut de Recherche et Coordination Acoustique/Musique) in Paris. In the code it is used [[https://github.com/victor-shepardson/rave-supercollider/tree/master][rave-supercollider]]. 

* How to use

** Running the MediaPipe Python Scripts

This instructions are for Linux, and the scripts has been tested only in Fedora Linux.

#+begin_src bash
  sudo dnf conda
  conda config --set auto_activate_base false # optional
  mkdir mediapipe
  conda create --name mediapipe python= 3.12
  conda activate mediapipe
  pip install mediapipe
  pip install python -osc
#+end_src

If the intention is to run the scripts that recognize the poses from pictures, the script need to be run within the terminal in the session where the conda environment =mediapipe= is active.

** Running the Supercollider Script

*** Installing Supercollider and the dependences

To install Supercollider and the sc3-plugins on Fedora, please follow thes [[https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-on-Fedora/c21f45bc9259d578c39862bf569f0f8c5373cecb][instructions]]. 

Also, it is needed to install FluCoMa and Rave-supercollider. Follow the [[https://learn.flucoma.org/installation/sc/][instructions for FluComa]], and the instructions for [[https://github.com/victor-shepardson/rave-supercollider/tree/master][Rave-supercollider]].



# *** Installing the necesary dependanced

# El repositorio aloja un instrumento cuyo diseño busca ser un campo de test para la politica de la interacción y el rol agencial de la inteligencia artificial en esta política.

# En este sentido el instrumento sigue cierto spatrones prersentes en su ciontraparte fisica. Su diseño se basa en la sumatoria de sintesis de sonido que proviene de la manipulación de espacios latentes de diferentes modelos. Su responsividad, al igual que los instrumentos físisco, solo se manifiesta somnoramente cuando existe cambio. La tasa de cambio modifica no solo la intensidad, sino que ademas la presencia de las diferentes voces espectrales. Po último, subitos cambios modifican el ataque del sonido. De esta forma se busca crear un instrumento que responda de forma intuitiva a los movimientos de los performers, a rapidos cambios asi como tambien a cambios sutiles.

# si bien existe una compoonente espacioal en el entrenamiento de la NN con poses, hay que considerar la componente temporal. Es ahi donde el rate de cambio sirve. Sin embargo, exsiitenm otros alcances que se podrian agregar en un futuro. 
